baseURL = "/the-great-pendragon-repo"
languageCode = "en-us"
title = "The Great Pendragon Campaign"
theme = "book"

[params]
## Book Theme Settings
### Book Theme
BookSection = "*"
BookCollapseSection = true
BookTheme = "dark"